source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "activerecord", "6.1.7.1"
gem "sinatra-activerecord"
gem "pg", "0.18.4"
gem "json"
gem "rack-test"
gem "data_mapper"
gem "puma"
gem "sinatra-cross_origin"
gem "rake"
gem "google-id-token"
gem "rack-ssl-enforcer"
gem "rerun"
