source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "activerecord"
gem "sinatra-activerecord"
gem "pg"
gem "json"
gem "rspec"
gem "rack-test"
gem "data_mapper"
gem "sprockets"
gem "puma", "3.12.4"
gem "sinatra-cross_origin"
gem "rake"
gem "google-id-token"
gem "rack-ssl-enforcer"
gem "heroku-deflater", :group => :production