source "https://rubygems.org"

ruby "2.6.3"

gem "sinatra"
gem "sinatra-contrib"
gem "activerecord", "5.0.0"
gem "sinatra-activerecord"
gem "pg"
gem "json"
gem "rspec"
gem "rack-test"
gem "data_mapper"
gem "sprockets"
gem "puma"
gem "sinatra-cross_origin"
gem "rake"
gem "google-id-token"
gem "rack-ssl-enforcer"
