development:
  adapter: postgresql
  database: development
  username: postgres
  host: localhost
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

test:
  adapter: postgresql
  database: test
  username: postgres
  host: localhost
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

production:
  adapter: postgresql
  database: production
  username: postgres
  host: localhost
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
