development:
  adapter: postgresql
  database: development
  username: changetoYourPSQLusername
  password: changetoYourPSQLpassword
  host: localhost
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

test:
  adapter: postgresql
  database: test
  username: changetoYourPSQLusername
  password: changetoYourPSQLpassword
  host: localhost
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  adapter: postgresql
  database: development
  username: changetoYourPSQLusername
  password: changetoYourPSQLpassword
  host: localhost
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
